all:
	g++ -c -I ./inc ./src/*.cpp
	g++ -I ./inc ./*o -o prog
	./prog 
# src=./src/*.cpp
# target=./bin
# INCFLAGS=-I ./inc
# CC=g++
# CCFLAGS=-Wall
# OBJECTS=bin/warrior.o  bin/ninja.o  bin/samurai.o bin/game.o
#
#
# compile: $(src)
# 	$(CC) $(CCFLAGS) $(src) -c $(INCFLAGS) -o $(target)
#
# run:
# 	./bin/prog
#
# clean:
# 	rm ./bin/*.o
# 	rm ./bin/prog
#
# all: clean compile run
